name: Type Checker
on: [pull_request, merge_group]

jobs:
  run:
    name: Type Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
      - run: pnpm install
        working-directory: frontend/app/kansha-game
      - run: pnpm lint
        working-directory: frontend/app/kansha-game
