name: Type Checker
on: [pull_request, merge_group]

jobs:
  run:
    name: Type Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3
      - run: pnpm install
        working-directory: frontend/app/kansha-game
      - run: pnpm lint
        working-directory: frontend/app/kansha-game
